[workspace]
resolver = "3"
members = ["ttd_sys", "ttd", "auto_unpack", "ttd_to_es"]

[workspace.package]
authors = ["Christophe Alladoum"]
version = "0.1.0"
edition = "2024"
description = "Rust bindings for Microsoft TTD"
readme = "./README.md"
license = "Apache-2.0"
repository = "https://github.com/hugsy/ttd-rust"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[profile.release-with-debuginfo]
inherits = "release"
debug = true
