[package]
name = "ttd"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc"]
rustdoc-args = ["--cfg", "docsrs"]
no-default-features = true

[lib]
crate-type = ["rlib"]

[dependencies]
ttd_sys = { path = "../ttd_sys", version = "0.1", default-features = false }
bitflags = "2.10.0"
chrono = "0.4.42"
derive_more = { version = "2.0.1", features = ["from", "debug", "display"] }
log = { version = "0.4.28", features = ["std"] }

[features]
default = ["replay"]
full = ["replay", "record"]

replay = ["ttd_sys/replay"]
record = []

[lints.rust]
unsafe_code = "forbid"
unused = { level = "warn", priority = -1 }
