name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        os:
          # - windows-2022 # missing `winget`
          - windows-2025
          # - windows-11-arm # not available for private repos
        build: [debug, release]

    name: ${{ matrix.os }}/${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
         key: ${{ matrix.os }}-${{ matrix.build }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
         path: |
             ~/.cargo/bin
             ~/.cargo/registry/index
             ~/.cargo/registry/cache
             ~/.cargo/git/db

      - run: |
          rustup update
          rustup component add rustfmt
          rustup show
          cargo install cargo-audit cargo-deny cargo-tarpaulin cargo-chef

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-deps
        env:
          cache-name: cache-deps
        with:
          key: cargo-${{ matrix.os }}-${{ matrix.build }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git/db
            ./target/debug/deps
            ./target/release/deps
          restore-keys:
            cargo-${{ matrix.os }}-${{ matrix.build }}-

      - name: Build (debug)
        if: matrix.build == 'debug'
        run: |
          cargo fmt --check
          cargo build --all-targets
          cargo clippy

      - name: Build (release)
        if: matrix.build == 'release'
        run: |
          cargo fmt --check
          cargo build --all-targets --release
          cargo clippy --release

      - name: Create Test Traces
        run: |
          ttd -acceptEula -out $env:TEMP\test -launch c:\windows\system32\cmd.exe "/c whoami"

      - name: Run Tests (debug)
        if: matrix.build == 'debug'
        run: |
          cp .\ttd*.dll .\target\debug\deps\
          cp .\ttd*.dll .\ttd_sys\ttd_ffi\build\tests\
          ctest --build-config Debug -T test --test-dir .\ttd_sys\ttd_ffi\build\tests
          cargo test

      - name: Run Tests (release)
        if: matrix.build == 'release'
        run: |
          cp .\ttd*.dll .\target\release\deps\
          cp .\ttd*.dll .\ttd_sys\ttd_ffi\build\tests\
          ctest --build-config Release -T test --test-dir .\ttd_sys\ttd_ffi\build\tests
          cargo test --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ttd_${{ matrix.build }}_${{ matrix.os }}_${{ github.sha }}
          if-no-files-found: warn
          path: |
            ./ttd_sys/ttd_ffi/install/ttd_ffi_tests/tests/*.exe
            ./ttd_sys/ttd_ffi/install/ttd_ffi_tests/tests/*.pdb
            ./ttd_sys/ttd_ffi/install/*.exe
            ./ttd_sys/ttd_ffi/install/*.pdb
            ./TTD*.dll
            ./target/**/*.rlib
            ./target/**/*.exe
            ./target/**/*.pdb
            ./target/**/*.dll
